<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AndresLaptop" ignored="0" name="Test Login Screen With Data Provider" tests="3" failures="1" timestamp="22 Jan 2023 14:39:05 GMT" time="31.923" errors="0">
  <testcase name="testMethod1" time="17.485" classname="Exercises.LessonTwentyOne.TestWithDataProvider"/>
  <testcase name="testMethod1" time="4.965" classname="Exercises.LessonTwentyOne.TestWithDataProvider"/>
  <testcase name="testMethod1" time="6.691" classname="Exercises.LessonTwentyOne.TestWithDataProvider">
    <failure type="java.lang.AssertionError" message="Verify login success popup detail message expected [Just using for test] but found [You are logged in!]">
      <![CDATA[java.lang.AssertionError: Verify login success popup detail message expected [Just using for test] but found [You are logged in!]
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.verifyCorrectEmailAndPassword(LoginTestFlowWithHardAssert.java:77)
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.verifyLogin(LoginTestFlowWithHardAssert.java:47)
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.performLogin(LoginTestFlowWithHardAssert.java:32)
at Exercises.LessonTwentyOne.TestWithDataProvider.testMethod1(TestWithDataProvider.java:16)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Test Login Screen With Data Provider -->
